### ISSUE TITLE
Balena OS ?

### ISSUE THREAD

**Issue by aessig** [RAKWireless/rak_common_for_gateway#10]
Has anyone been able to run it with Balena OS ?

**Comment by dapendragon** [comment]
That would be a fantastic feature. I've tried several things for my RAK 7243, but never been able to get Balena working with it. I know of several others that have RAK 831-based versions running on Balena successfully. See https://github.com/jpmeijers/ttn-resin-gateway-rpi for other attempts.

**Comment by dapendragon** [comment]
This now works with my RAK 7243 for TTN V3: https://www.balena.io/blog/deploy-a-basics-station-lora-gateway-with-ttn-and-balena/
