### ISSUE TITLE
Raspberry RAK2245´96 board

### ISSUE THREAD

**Issue by pacmenDE** [RAKWireless/rak_common_for_gateway#2]
Hi,
i ve bougt a wrong version of RAK2245.
I would like to us with raspi zero w. I used this repo for raspi setup and the device is wired as descriped from the User manual RAK2245 96 board with the standart pinouts of raspi zero. But it´s not running. 
Have you any idea? is the standart pinmap changed?

What i´ve done.

./test_loragw_reg

- Beginning of test for loragw_reg.c

ERROR: CONCENTRATOR UNCONNECTED
IMPLICIT_PAYLOAD_LENGHT = 0 (should be 197)
FRAME_SYNCH_PEAK2_POS = 0 (should be 11)
PREAMBLE_SYMB1_NB = 0 (should be 49253)
ADJUST_MODEM_START_OFFSET_SF12_RDX4 = 0 (should be 3173)
IF_FREQ_1 = 0 (should be -1947)
End of test for loragw_reg.c

pi@rak-gateway:/opt/ttn-gateway/lora_gateway $ sudo ./reset_lgw.sh stop
Accessing concentrator reset pin through GPIO7...
pi@rak-gateway:/opt/ttn-gateway/lora_gateway $ sudo ./reset_lgw.sh start
Accessing concentrator reset pin through GPIO7...

Thanks for help
Regadrs,
Patrik

**Comment by RAKWireless** [comment]
@pacmenDE 
I am very sorry to see your message so late.
Please go to the /opt/ttn-gateway/packet_forwarder/lora_pkt_fwd directory and use start.sh instead of reset_lgw.sh
