### ISSUE TITLE
Install script not working for TTN

### ISSUE THREAD

**Issue by lloydXmas** [RAKWireless/rak_common_for_gateway#23]
When running the main install script `sudo ./install.sh` and selecting RAK2245, the installer seems to proceed with a complete setup for Chirpstack and skips any TTN configurations. Running `sudo gateway-config` and selecting `Server is TTN` still does not add anything to `/opt/ttn-gateway/`. `ttn-gateway.service` is also missing once the install is finished.

**Comment by lloydXmas** [comment]
It seems that the issue happens when cloning directly from the master branch. Downloading release 4.2.0 and running the installer works fine for TTN.

**Comment by RAKWireless** [comment]
Hello, @lloydXmas ! Sorry this is a bug for us, we have fixed it.
