### ISSUE TITLE
packet_forwarder version number not updated

### ISSUE THREAD

**Issue by hdtodd** [RAKWireless/rak_common_for_gateway#29]
At least for RAK2245, the packet_forwarder version number is stuck at 4.0.1 and doesn't update when the baseline code is updated.  Should be 4.2.3R, according to the JSON file, but the file 
./lora/packet_forwarder/VERSION seems to be the value used to set VERSION in the Makefile, and its value is incorrect.  Looks like that file is in one of the packages downloaded with "apt".  You might consider modifying the Makefile so that the version number is set from the JSON file rather than the file named "VERSION", so there would only one place to edit to change the version number when the baseline code is update.

**Comment by RAKzhuqi** [comment]
The version number of 4.2.3R is for the source code of rak_common_for_gateway, which can be checked through gateway-version after installation.

The version number (4.0.1) in the ./lora/packet_forwarder/VERSION file is the version number of https://github.com/Lora-net/packet_forwarder.

**Comment by hdtodd** [comment]
@RAKzhuqi 
Thanks for clarifying.  I'll reset my VERSION file to 4.0.1
