### ISSUE TITLE
loraserver doesn't install

### ISSUE THREAD

**Issue by shinukamo** [RAKWireless/rak_common_for_gateway#3]
install file points to old loraserver.io packages that have been removed

**Comment by mhalenka** [comment]
Same here.

**Comment by RAKWireless** [comment]
This problem has been fixed in 2019-08-27.

**Comment by rtrainer** [comment]
Still a problem

**Comment by RAKWireless** [comment]
> Still a problem
I am very sorry that my update is late!
We have modified the bug you mentioned and modified some other features.
You can view the updates in the README.

**Comment by RAKWireless** [comment]
@rtrainer 

I am very sorry that my update is late!
We have modified the bug you mentioned and modified some other features.
You can view the updates in the README.
