### ISSUE TITLE
makefile for packetforwarder 

### ISSUE THREAD

**Issue by sajalbhargava** [RAKWireless/rak_common_for_gateway#32]
i am trying to makefile for packet forwarder but error is coming "config.h " not found.
any help will be appreciated

**Comment by cstratton** [comment]
Normally config.h is autogenerated from library.cfg when you build the lora gateway HAL.

Are you not using the install script but trying to build this yourself?  If so, you'll need to checkout and build https://github.com/Lora-net/lora_gateway.git first, as the install.sh script does
