### ISSUE TITLE
Chirpstack Channel plans shifted

### ISSUE THREAD

**Issue by ThHobo** [RAKWireless/rak_common_for_gateway#40]
It would seem that when selecting a channel plan from the configuration of script the Channel plans are shifted. If you choose one you get the configuration for the packet forwarder for the one before it in the list.
![image](https://user-images.githubusercontent.com/39050240/99583150-c3904f00-29eb-11eb-98a4-6510630f13c6.png)

So if for example as in the image you choose 6 IN865, you will instead get 5 EU868.

**Comment by TaylorIsAGoodboy** [comment]
fixed it
