### ISSUE TITLE
domain_name_server for eth0 in /etc/dhcpcd.conf is not setting

### ISSUE THREAD

**Issue by vbulbul** [RAKWireless/rak_common_for_gateway#44]
After configuring LAN IP address domain_name_server is not set in /etc/dhcpcd.conf. As a default google DNS can set or asked for user DNS ?
Example;
# WARNING:Do not delete or modify the following 5 lines!!!
# RAK_eth0_IP
interface eth0
static ip_address=192.168.1.10
static routers=192.168.1.1
static domain_name_servers=8.8.8.8 8.8.4.4

**Comment by enric-lee** [comment]
we use 192.168.10.10 for first connect,  thus we can configure Gateway with PC via ssh.  You can change it.
