### ISSUE TITLE
Fix for DietPi

### ISSUE THREAD

**Issue by x893** [RAKWireless/rak_common_for_gateway#5]
Hi,
for DietPi OS need add
**apt install build-essential net-tools -y**
in rak/install.sh (for example before apt install git ppp dialog jq minicom monit -y)
and need check hciuart enabled because
**systemctl disable hciuart**
not installed and script fail.

Best regards

**Comment by RAKWireless** [comment]
Thank you very much. I have paste this content to readme file so that other users can see it when they use DietPi OS.
