### ISSUE TITLE
Chirpstack not installed on RPi CM4

### ISSUE THREAD

**Issue by JeroenIoT** [RAKWireless/rak_common_for_gateway#52]
During installation of the RAK 2245 on a Raspberry Pi Compute Model 4

* Installation went smooth without error
* However Chirpstack is not installed 

After some investigation the cause was found

* RPi CM4 is not "OKed" during installation
* `do_get_rpi_model()` checks the rpi model (see  `~/rak_common_for_gateway/rak/rak/shell_script/rak_common.sh`)
* Added the following line in `do_get_rpi_model()` to allow ChirpStack to be installed on the RPi CM4 as well
 
```
    # Added for support of the "Raspberry Pi Compute Module 4 Rev 1.0" (DeBuffel)
    if [ $model -eq 255 ]; then
        text=`tr -d '\0' </proc/device-tree/model | grep -a 'Pi Compute Module 4'`
        if [ ! -z "$text" ]; then
            model=4
        fi
    fi
```
ChirpStack and RAK gateway work fine after the above changes (CM4 with RAK2245 hat)
See also https://forum.rakwireless.com/t/installation-rak2245-chirpstack-not-installed/4432

**Comment by enric-lee** [comment]
Thank you for your suggestion.  We will add it when our CM4 carryboard is OK.
