### ISSUE TITLE
Where to see sensor data sent from node

### ISSUE THREAD

**Issue by NelsonKon** [RAKWireless/rak_common_for_gateway#53]
Hi,
My sensor node has joined in the LoRa RAK2243 gateway.  
At the web-based platform, I go to Application->AppB (I created this)->Devices->ContLashSens3 (I created this).

Then I go to DEVICE DATA tab and LORAWAN FRAMES tab.  I can see that there are update (as attached).  My sensor node sends data to the gateway every 10s.

![Screenshot from 2021-08-26 12-55-40](https://user-images.githubusercontent.com/72735512/130906449-6ff4858d-530d-4d04-b44c-be18fdba2162.png)
![Screenshot from 2021-08-26 12-57-01](https://user-images.githubusercontent.com/72735512/130906472-07208ebb-55f4-489c-8d86-ec96888cab4c.png)

But where can I see the data sent by my node?

Hope to hear from you soon.

Regards,

**Comment by TaylorIsAGoodboy** [comment]
You cat see your data on Device Data.  Just as bellow:
![image](https://user-images.githubusercontent.com/76980983/132188820-69958577-3592-4677-987a-ea2b49a092a3.png)

**Comment by NelsonKon** [comment]
Hi Taylor,
Thanks for your reply.  I can see it already.
But don't you think that it is quite troublesome that we always need to expand it to see the data?

Is there a way to see the data at a glance, like in a page?

I tried to use influxDB and Grafana.  I am able to see the data in the table form.  But the graph can't be plotted out.  I don't know why.  I am using Grafana v8.1.2.

Hope to hear from you soon.

Regards,

**Comment by Scobber** [comment]
I think you will find where you are looking at the data is intended for debugging purposes.
the RAK gateway forms a small part of a overall system, as does chirpstack. 
What you are posting to in reference here is off topic, and should be placed elsewhere.

You need to look at designing a overall solution. you have the RF side working, you have chirpstack working. its time to take the data from chirpstack and store and retreive it. which are completely separate elements. 

perhaps you should be asking in a influx or grafana community.

**Comment by enric-lee** [comment]
Yes, influxDB and Grafana can do this work.   You should decode your data into object data as https://github.com/RAKWireless/RUI_LoRa_node_payload_decoder

If you configure chirpstack integration with influxDB, the decoded data will be restored in infuxDB.  Then you can use grafana connect influxDB and display the data.

**Comment by NelsonKon** [comment]
Hi Enric,
Thanks for your reply.  I did as what you mentioned.  Just that the data can't be plotted out in graph form.  Could it be my javascript problem?

This is my javascript Decode function

function Decode(fPort, bytes, variables) {
  if(bytes.length == 1) {
      if(bytes[0] == 1) {
         return {
            'button': 'activated'
         }
      } else {
         return {
            'error': 'button action unknown'
         }
      }  
  } else {
      var pkFreq = '';
      var cnt;
      
      for (cnt = 0; cnt < bytes.length; cnt++) {
      	
        if ((bytes[cnt] >= 48) && (bytes[cnt] <= 57)) {
          	pkFreq += String.fromCharCode(bytes[cnt]);
        }

      }
      
        return {
            'pkfrequency': pkFreq            
        }      
   }  
}

Could it be something left out and causes the graph can't be plotted?

Regards,

**Comment by NelsonKon** [comment]
Hi Taylor, Enric and Scobber,
I found the cause of why graph can't be plotted.

It is because my variable pkFreq has to be in number.  Currently it is in string form.  That's why it can't be plotted.

I have to convert it to number like this
'pkfrequency': parseInt(pkFreq)

Then it can be plotted out.

Thanks so much for your guidance.

Regards,
