### ISSUE TITLE
Installation issue RAK5146(USB) with TTN

### ISSUE THREAD

**Issue by nmaas87** [RAKWireless/rak_common_for_gateway#57]
After having the RAK5146(USB) / RAK5146-226  installed in TTN mode and added it to TTN, no data ever arrives.
I needed to manually change the "server_address": "router.us.thethings.network" to eu1.cloud.thethings.network - otherwise it never comes online. Do I need to change anything else?

**Comment by TaylorIsAGoodboy** [comment]
Yes, you only need to modify url.
