### ISSUE TITLE
Will it support RAK7271 gatway model?

### ISSUE THREAD

**Issue by lawrence870521** [RAKWireless/rak_common_for_gateway#59]
Hi, I just bought this gateway recently. Will this gateway model be supported in the future?

**Comment by TaylorIsAGoodboy** [comment]
![image](https://user-images.githubusercontent.com/76980983/133713002-52622924-31b4-45ad-9b76-5975ed5c9b40.png)
You can use RAK2287 USB directly.
More information, please read https://docs.rakwireless.com/Product-Categories/WisGate/RAK7271-7371/Datasheet/#models-bundles
