### ISSUE TITLE
Raspberry Pi Zero support

### ISSUE THREAD

**Issue by mapl** [RAKWireless/rak_common_for_gateway#6]
why has the Raspberry Pi Zero support been removed?

**Comment by RAKWireless** [comment]
@mapl 
We have not removed support for Raspberry Pi 0.

**Comment by mapl** [comment]
Good to know :) I am referring to 
..
6.Install chirpstack only on Raspberry Pi 3 and Raspberry Pi 4.
..
which got me confused.

**Comment by RAKWireless** [comment]
Because Pi Zero can't run ChirpStack successfully. So there is no built-in ChirpStack in Pi Zero.
