### ISSUE TITLE
building rak2247_usb on debian buster failed

### ISSUE THREAD

**Issue by przemekgalazka** [RAKWireless/rak_common_for_gateway#61]
Hello,

as probably in Debian buster, the lib libftdi-dev has changed and tag v4.2.8 is not building on this newest Debian. It is building on stretch version.

We get errros as follow:
/usr/bin/ld: 
[main]     fast.o:/opt/lora-rak-gateway/dev/rak_common_for_gateway/lora/rak2247_usb/libmpsse/src/mpsse.h:221: multiple definition of `fast_rw_buf'; 
[main]     mpsse.o:/opt/lora-rak-gateway/dev/rak_common_for_gateway/lora/rak2247_usb/libmpsse/src/mpsse.h:221: first defined here
[main]     
[main]     
[main]     /usr/bin/ld: 
[main]     support.o:/opt/lora-rak-gateway/dev/rak_common_for_gateway/lora/rak2247_usb/libmpsse/src/mpsse.h:221: multiple definition of `fast_rw_buf'; mpsse.o:/opt/lora-rak-gateway/dev/rak_common_for_gateway/lora/rak2247_usb/libmpsse/src/mpsse.h:221: first defined here
[main]     
[main]     collect2: error: ld returned 1 exit status
[main]     
[main]     make: *** [Makefile:21: mpsse] Error 1

**Comment by cstratton** [comment]
This is a known issue in the external libmpsse repo

https://github.com/devttys0/libmpsse/issues/11
