### ISSUE TITLE
spam to syslog

### ISSUE THREAD

**Issue by pro-ject** [RAKWireless/rak_common_for_gateway#64]
master branch
raspberrypi 4
rak2287(spi + gps)

Fill the /var/log/syslog:
Oct 28 23:55:55 raspberrypi ttn-gateway[2277]: WARNING: [gps] read() returned value 0
Oct 28 23:55:55 raspberrypi ttn-gateway[2277]: WARNING: [gps] read() returned value 0
Oct 28 23:55:55 raspberrypi ttn-gateway[2277]: WARNING: [gps] read() returned value 0
Oct 28 23:55:55 raspberrypi ttn-gateway[2277]: WARNING: [gps] read() returned value 0

~100MB per minute

**Comment by TaylorIsAGoodboy** [comment]
Thank you for your report, we will fix it ASAP.

**Comment by TaylorIsAGoodboy** [comment]
fixed it.
